### ISSUE TITLE
No recording being made to the dashboard

### ISSUE THREAD

**Issue by IvanClair** [smartlook/smartlook-android-sdk#10]
Hi, I encounter an issue, no recordings are being made to the dashboard after hit Smartlook.start() in Activity A, then hit Smartlook.pause() in Activity B. Found device system keep logging same message as below

log 
2018-12-05 15:01:46 I/MPEG4Writer: setStartTimestampUs: 0
2018-12-05 15:01:46 I/MPEG4Writer: Earliest track starting time: 0
2018-12-05 15:01:47 D/MPEG4Writer: Video track stopping. Stop source
2018-12-05 15:01:47 D/MPEG4Writer: Video track source stopping
2018-12-05 15:01:47 D/MPEG4Writer: Video track source stopped
2018-12-05 15:01:47 I/MPEG4Writer: Received total/0-length (31/0) buffers and encoded 31 frames. - Video
2018-12-05 15:01:47 D/MPEG4Writer: Video track stopped. Stop source
2018-12-05 15:01:47 D/MPEG4Writer: Stopping writer thread
2018-12-05 15:01:47 D/MPEG4Writer: 0 chunks are written in the last batch
2018-12-05 15:01:47 D/MPEG4Writer: Writer thread stopped
2018-12-05 15:01:47 I/MPEG4Writer: Ajust the moov start time from 0 us -> 0 us
2018-12-05 15:01:47 D/MPEG4Writer: Video track stopping. Stop source

**Comment by adamblack** [comment]
Hello @IvanClair ,

log seems to be ok. When you use SDK without start/pause methods, do you see any recordings in the dashboard?

Also, we are currently uploading any data only on wifi. Maybe that is the issue?

**Comment by IvanClair** [comment]
Hi @adamblack ,
I tried to use SDK without start/pause, but still no recordings on dashboard, and i am very sure the device has WIFI connection

**Comment by IvanClair** [comment]
@adamblack 

any suggestion?

**Comment by adamblack** [comment]
Hello @IvanClair ,

we just released new version: https://smartlook.github.io/docs/sdk/android/

Could you give it a shot and tell me if you are still having issues?

Is your app somewhere public i.e. in Google Play? Also, exactly where are you calling init function?

Would it be possible to send me an email at adam@smartlook.com with the information under which email you registered to Smartlook? With that information, we could also start debugging our backend services.

Thanks!

**Comment by IvanClair** [comment]
Hi @adamblack 

I updated the version number in the doc link you provided, but our project on dashboard is out of beta now ... can you help us about that? contact darisha@travelstart.com or pia@travelstart.com

It is our Google Play link [Flapp](https://play.google.com/store/apps/details?id=za.co.travelstart.flapp), but we have not publish this feature to Google Play yet

I called the init function in `onCreate` method of a class which extends `Application`, and this is our api key : 2f206c8dff565d1be48220150e3506cc0071aa5e

and sorry i am not sure the register email, maybe darisha@travelstart.com, can you use the api key or company name "TravelStart" to confirm the email?

**Comment by darisha30** [comment]
Hi Adam

I have registered the account with Darisha@travelstart.com.

Please let me know if there is anything else you will need from me related to the smartlook integration.

@Ivan Kuo<mailto:ivan@travelstart.com> please let me know if there is anything else needed.

@Steven Lin<mailto:steven@travelstart.com> and @Eric Chen<mailto:eric.chen@travelstart.com> does the smartlook still crash the ios app?  We should also try to have this resolved.

Kind regards
Darisha

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
