### ISSUE TITLE
Layout and views over Google Maps have transparent background

### ISSUE THREAD

**Issue by LukasVykuka** [smartlook/smartlook-android-sdk#17]
Expected
![smartlook-expected-snip](https://user-images.githubusercontent.com/8152190/53966473-87bc3580-40f3-11e9-81ad-dccc4ed6f696.png)

Actual
![smartlook-actual-snip](https://user-images.githubusercontent.com/8152190/53966478-8ab72600-40f3-11e9-8969-dfe8b682be9e.png)

**Comment by adamblack** [comment]
Hello @LukasVykuka ,

currently we are not able to quickly fix / change how we grab screenshots since we need to merge different layers (map is rendered to different layer than native views). We will try our best to improve the behaviour, but it is not a top priority right now. :/
