### ISSUE TITLE
Skewed resolution

### ISSUE THREAD

**Issue by ppetarr** [smartlook/smartlook-android-sdk#18]
We're currently testing out the Smartlook SDK on both iOS and Android. On iOS the SDK runs smoothly, however on Android there is an issue on certain devices. 

The video recording is shown as a skewed/stretched resolution and is not at all clear.

Details

- Pixel 3 XL
- Android 9
- Smartlook SDK `0.9.0.2.5.7-beta`

This issue happens 100% of the time on the Pixel 3 XL

This is what the recording looks like:
<img width="817" alt="Screen Shot 2019-06-06 at 9 33 52 AM" src="https://user-images.githubusercontent.com/3605377/59037004-59f3a380-883e-11e9-833f-4782f55705b9.png">

**Comment by SenNeonoveNoci** [comment]
@ppetarr Thanks for the report! We gonna look into it and keep you updated.

**Comment by SenNeonoveNoci** [comment]
@ppetarr We tested our SDK on Pixel 3 XL but could not reproduce the issue.

Can you send us some kind of link to your app or APK so we can figure out the cause and situation when the bug occurs?

**Comment by ppetarr** [comment]
@SenNeonoveNoci I'll see about sending an `apk` but I did notice one thing. When we launch our first screen (Login) the resolution seems fine however we can only see the top half of the screen, and then once we get to the main page shown above, the resolution is the result.

**Comment by ppetarr** [comment]
@SenNeonoveNoci can we share a link through support rather than publicly?

**Comment by adamblack** [comment]
Hi @ppetarr,

you can contact our support for sure, however would you be willing to visit our Discord (https://discord.gg/SbEt98m) where we can have private real time conversation? :]

**Comment by ppetarr** [comment]
@adamblack sure thing, I can join in about 20 mins

**Comment by ppetarr** [comment]
Hey @adamblack we had joined the discord but we received no message from anyone regarding anything, should we message someone specific on there?

**Comment by Acro** [comment]
@ppetarr What's your Discord username?

**Comment by ppetarr** [comment]
@Acro FiixSoftware
