### ISSUE TITLE
Dialogs in DialogFragments are not recorded

### ISSUE THREAD

**Issue by Pitel** [smartlook/smartlook-android-sdk#24]
There is just click event to empty space on the video.

Using AndroidX versions of AlertDialog and DialogFragment classes.

**Comment by Pitel** [comment]
Hmm, just noticed some dialogs are visible. Maybe it depends on use of childFragmentManager?

**Comment by SenNeonoveNoci** [comment]
We gonna investigate this as soon as we fix crashes and high priority issues. Will keep you updated.
