### ISSUE TITLE
[Unity][Android] Crash 

### ISSUE THREAD

**Issue by kdzapp** [smartlook/smartlook-android-sdk#28]
```
Caused by java.lang.IllegalArgumentException
attempt to remove OnFrameMetricsAvailableListener that was never added
com.smartlook.sdk.smartlook.analytics.c.a.a.b
```

Not sure why this is happening. I have a conflict with some other library also using the http lib you all are using, so I tried out using the gradle version and this is the error I get. It crashes my app too.

**Comment by kdzapp** [comment]
`Program type already present: okhttp3.Authenticator$1`
If I try to use .aar lib

**Comment by adamblack** [comment]
Hello @kdzapp ,

new version is up - fixing the issue you mentioned in first post: https://smartlook.github.io/docs/sdk/unity/

We are planning to release new version soon handling dependency issue but until that please use gradle installation.

**Comment by kdzapp** [comment]
Thanks!~
