### ISSUE TITLE
Smartlook slows down the entire app

### ISSUE THREAD

**Issue by dnhyde** [smartlook/smartlook-android-sdk#36]
Hi,
I integrated smartlook following the [docs](https://smartlook.github.io/docs/sdk/android/). 

I have:
`Smartlook.setupAndStartRecording(<SMARTLOOK_API_KEY>);`
initialized it in the Application class as suggested in the docs.
> Best place to call one of these methods is in Application class or any entry point to your app.

My question is already answered in the [help section](https://www.smartlook.com/help/will-smartlook-slow-mobile-app/), saying that smartlook won't slow down my app, but even with the smallest fps settings I can see a lag every second when smartlook takes the screenshot of my app.

phone: Xiaomi Redmi 5 plus
android version: 8.1.0
phone: Huawei Y6 2019
android version: 9

**Comment by SenNeonoveNoci** [comment]
Hi, @dnhyde,

may I ask you some question:

What version of SDK are you using?
How complex is your layout? 
Are you using some Surface Views, Maps, etc. ? 
Does this happen only on `Xiaomi Redmi 5 plus` and `Huawei Y6 2019` or on other devices too?

Also please email me your SDK `API key` to frantisek@smartlook.com, or DM me on Discord.

**Comment by dnhyde** [comment]
Thanks for your quick reply,
Indeed I use a GLSurfaceView (GLTextureView) with a camera preview with its dedicated [GLRender](https://developer.android.com/reference/android/opengl/GLSurfaceView.Renderer). Moreover the layout has an androidx [cardView](https://developer.android.com/reference/androidx/cardview/widget/CardView) in it, which uses SurfaceFlinger as well if I remember correctly.
I joined discord we can update the issue when we have a solution thanks

**Comment by SenNeonoveNoci** [comment]
Discussion continued on Discord.
