### ISSUE TITLE
Random Crash when using default installation in Android 7

### ISSUE THREAD

**Issue by emtt** [smartlook/smartlook-android-sdk#38]
Samsung SM-N920G (Note 5)
Android version 7.0

Installation:
App.java (extends Application)
`Smartlook.setupAndStartRecording(SMARTLOCK_API);`

The above line it's the only setup that I made.

Later the crashes begun:
**E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /data/user/0/com.mvs.digital/files/sessions/W8EKI33AX9839IODJV/video_images/28/0.jpg (Too many open files)**

How I fixed? I don't did it. I changed the setup.

In App.java change the configuration fps to:
Smartlook.setupAndStartRecording(SMARTLOCK_API, false, 1);

I think the lib must be aware about the poor specs of the device to operate and prevent crashes and decrease automatically the fps.

**Comment by SenNeonoveNoci** [comment]
Hi @emtt,

I'm gonna look into your issue. I have just one question now. If you changed fps to 1, the problem is still occurring or does it happen when fps is higher?

**Comment by emtt** [comment]
Hi @SenNeonoveNoci.

I can confirm it still happening when the FPS is  set to 1. Sadly turned off the lib for now because of this.

**Comment by adamblack** [comment]
Hi @emtt ,

we did few modifications regarding the video handling. Please open new issue with logcat as well in case this issue is still applicable. Newest version is currently 1.4.2
