### ISSUE TITLE
Questions about api and use of lib

### ISSUE THREAD

**Issue by thiagopneto** [smartlook/smartlook-android-sdk#4]
Hey guys,

Me and my team, we are on test period of smartlook's api for our android app.

I have some questions about the api.

1) Do you have a stable release with documentation? Or any prevision to release the current beta that is available on the docs?

2) We are trying to use the tracking method with additional data option - `track(@NonNull String eventName, JSONObject eventProperties)` - but we didnt know what the structure possible to set this additional data. I've tried something like creating a json object and put client name as propertie, for example. This data never  appeared in any event. Could you show me some example?

3) Now, on the dashboards, when we add events that were automatically tracked, like a click in a button, this event never get counted or get available to add in the funnels. Watching the video that explain this function and trying on our app, this didnt worked. Could you send me an example?

For all this questions, if you have an project with all examples of usage it will be very useful. 

Well. Thanks and if you need more info, let me know.

Regards.
Thiago Pimentel.

**Comment by Acro** [comment]
I will answer the 3rd one.

I just checked this, the `clicked element` event creation is broken in the current release. We are on this first thing tomorrow morning. In general, you should be able to
- select anything from the auto-complete and use it straight away
- define certain button identifier regardless of the Activity it was in

Once this is fixed, we will provide examples of how to use this.

**Comment by adamblack** [comment]
Hi @thiagopneto ,

1) Important stuff regarding the SDK can be found at: https://smartlook.github.io/docs/sdk/android/ So far we are still in beta and we are not sure when we are going to release super-stable version of the SDK since there might still be a lot of corner cases to cover. Currently we gather data and you can always contact us in case of any issues.

2) Currently we do not show eventProperties JSON in the dashboard but it should be there really soon. You can send whatever you want in the JSON with one rule, we handle only JSONs with depth of 1. But you can send any map, String, Number, ...

**Comment by thiagopneto** [comment]
@adamblack and @Acro 

Thank you guys for the answers.

This additional data are very important for our project. So, we will take a brake with the tests and try back soon.

Regards. 
Thiago Pimentel.

**Comment by Acro** [comment]
Good news.

The `clicked element` event creation should now work as expected.
 
<img width="563" alt="screenshot 2018-11-22 at 09 57 08" src="https://user-images.githubusercontent.com/591096/48893220-23c17a00-ee40-11e8-8a95-e17f2bdad007.png">

As for the `eventProperties` for in custom events, those data should now be accessible in the event pop-up window in player.

<img width="351" alt="screenshot 2018-11-22 at 10 08 20" src="https://user-images.githubusercontent.com/591096/48895190-ca0f7e80-ee44-11e8-9e59-c87db84aaa53.png">

Please note all of these features are available with the [latest version of the SDK](https://smartlook.github.io/docs/sdk/android/).
