### ISSUE TITLE
Ionic event tracking not working

### ISSUE THREAD

**Issue by AlvaroCavalcante** [smartlook/smartlook-android-sdk#43]
- Platform
  - Android
- Technology
  - Ionic 4.11.10
- Problem description

I am trying to track the events in my mobile app made in ionic, but watching the user's recordings I saw that all click actions had the same value: **"MainActivity SystemWebView UNKNOWN"**
this is untraceable, what can I do?
I added the smartlook recording to my app module and app component

**Comment by SenNeonoveNoci** [comment]
Hi @AlvaroCavalcante,

native SDK can track clicks on native views. Ionic is sadly just a webpage displayed in `WebView`, we are detecting clicks on on `WebView` but cannot determine what element of website was clicked.

We might research some options in the future. For now, I'm gonna recommend you to use `Smartlook.trackCustomEvent()`. You need to define events by your self sadly.
