### ISSUE TITLE
Massive Performance Issues 

### ISSUE THREAD

**Issue by bstillitano** [smartlook/smartlook-android-sdk#5]
Hey guys,

I am aware that the android SDK is in beta at the moment and is undergoing heavy development. I just wanted to let you know that when the SDK is initialised, it causes huge performance issues.

Examples below:
• Open an AlertDialog (w/out Smartlook = ~.5s w/Smartlook = ~3.5s)
• Switch Tab (w/out Smartlook = ~.8s w/Smartlook = ~1.8s)
• Open an Activity (w/out Smartlook = ~.5s w/Smartlook = ~2.5s)

**Comment by adamblack** [comment]
Hi @bstillitano ,

are you using SL in app that is already released? (So we could check that i.e. on Play Store)

Do you use any "special" views like Texture/Surface? -> Is there anything special that could help us to simulate mentioned behaviour so we can fix that? :]

You can also contact me at adam@smartlook.com if it is more convenient for you.

Thanks!

**Comment by bstillitano** [comment]
Hey @adamblack I'm not using this in a production app at the moment. Our app is still in development.

I am using views only provided by AppCompat or SupportLibrary through gradle. 

If it helps, there are other network calls in our app using Retrofit2

**Comment by adamblack** [comment]
@bstillitano Got it.

So, would it be possible to send me data from Profiler in Android Studio? Ideally CPU/Memory record while using SDK. Sample/Trace Java methods. -> So far we did not have any issues regarding the performance so I need some data to start with. :/

You can send that to my email address so we do not share private info in public GH thread. :]

**Comment by bstillitano** [comment]
I don't have anything I can share as I am working on large business projects, but the issue seems quite reproducable. Simply installing it to an app with a bottomnav and nested fragments seems to repro the issue.

**Comment by adamblack** [comment]
Hi @bstillitano ,

we were not able to simulate same issue but new version is released. We fixed few performance issues so hopefully it is going to be ok.

You can always open new issue in case there is something broken.

Adam
