### ISSUE TITLE
ANR Crash

### ISSUE THREAD

**Issue by guqh** [smartlook/smartlook-android-sdk#50]
![image](https://user-images.githubusercontent.com/17330238/82881485-5935af00-9f72-11ea-8267-0785366c27ef.png)
![image](https://user-images.githubusercontent.com/17330238/82881519-62268080-9f72-11ea-99cf-dc903ab1f04c.png)

操作流程：
1. 我正常的根据API 接入后，网络连接正常的情况下，一切正常
2. 当我先连接网络，然后初始SDK后，启动录制，然后断开网络，Smartlook.trackCustomEvent(tag);
就会出现上面的log ，然后 crash 。

**Comment by SenNeonoveNoci** [comment]
@guqh Is this crash not occurring anymore, or why have you closed this issue?
