### ISSUE TITLE
Recorded session are being displayed in active session || Recording Not stoping automatically

### ISSUE THREAD

**Issue by Sahilpuri007** [smartlook/smartlook-android-sdk#54]
HI , using latest version of sdk

In Base Application class I Smartlook.setupAndStartRecording(BuildConfig.SMARTLOOK_SDK_KEY);

initialized and started recorrding

But Where to call stopRecording() if it will not stop by itself.

**Comment by SenNeonoveNoci** [comment]
Hi, @Sahilpuri007 recording stops itself on application closure. No need to call `Smartlook.stopRecording()` explicitly.

You can use `Smartlook.stopRecording()` to stop recording during application run.
