### ISSUE TITLE
Filter Recordings by custom user property

### ISSUE THREAD

**Issue by adesso-synak** [smartlook/smartlook-android-sdk#6]
Hello guys,
I would like to filter recordings by custom user property which I can set through JSONObject which I am calling identify method from Smart look SDK with... We are developing app which is connecting more mobile devices together and We would like to see all recording from all device which belongs to specific group (set through mentioned JSONObject property). 

Right now If I want to filter Recording, I can only select filter for predefined User properties.

**Comment by Acro** [comment]
Hello,

properties passed in using `identify` method from the Android SDK are now available as a filter in the dashboard.

You can find the filter under this path - `Recordings` > `Create filter` > `API identification`.

Both the keys and values should now be auto-completed.

<img width="560" alt="screenshot 2018-11-22 at 09 50 02" src="https://user-images.githubusercontent.com/591096/48891686-58cbcd80-ee3c-11e8-98da-1e23749c29b1.png">
