### ISSUE TITLE
Mapbox map not recorded

### ISSUE THREAD

**Issue by ericsvg** [smartlook/smartlook-android-sdk#7]
Hey,

I've just started giving your SDK a try and unfortunately the Mapbox map of my app isn't being recorded (it appears black). I believe they use a `GLSurfaceView` for rendering, I tried passing true as a second parameter to `Smartlook.init()` but that didn't fix the issue.

Is there anything to do to make it work?

SDK Version: 0.9.0.1.7.0-beta

**Comment by adamblack** [comment]
Hi @Jukurrpa ,

maps / mapbox recording is not available at the moment. :x

We are going to add this feature in the future but it is not so straightforward and we cannot do it easily out of box as recording of other elements. However it should be finished soon.

**Comment by ericsvg** [comment]
Hi Adam, thanks for your answer. Would you have an ETA for it by any chance?

**Comment by adamblack** [comment]
Hi @Jukurrpa ,

I think we should be able to deliver that feature in few weeks.

Will let you know once it is done. In case you want me to contact you directly i.e. via email, feel free to drop me a message at adam@smartlook.com :]

**Comment by ericsvg** [comment]
Sounds good, thanks a lot!

**Comment by adamblack** [comment]
Hello @Jukurrpa ,

we just released new version. You can find instructions on how to record maps in SDK docs: https://smartlook.github.io/docs/sdk/android/

In case you have any issues or you want us to do any additional tweaks, feel free to contact me directly at adam@smartlook.com
